### ISSUE TITLE
错误的缓存状态导致 DNS 解析失败

### ISSUE THREAD

**Issue by qwqVictor** [tuna/freedns-go#7]
最近我发现有些域名无法解析。检查日志之后发现缓存的问题可能是元凶。
过程如下：
![dig command](https://user-images.githubusercontent.com/21100901/89163212-d3546680-d5a7-11ea-866b-a22031cdc4c9.png)
我向 FreeDNS-Go 询问 login.live.com 的 DNS 解析记录。很明显它选择的是干净的上游，但此时应该是发生了错误而返回了一个空结果，没有 SOA 记录。  
![log](https://user-images.githubusercontent.com/21100901/89163559-570e5300-d5a8-11ea-9658-95817f64261e.png)
检查日志之后发现在请求上游时出错，但是之后它使用“缓存”里的内容来应答客户端今后的请求。显然从空缓存中是什么都得不到的。  
经过对相同域名的测试，我确定上游都可以正常解析。
这个问题偶尔会发生，目前还无法稳定复现。
系统环境：Debian 10 Buster，FreeDNS-Go v2020.1.16

---

Recently I found that some domain names failed to resolve. After checking the log, I assume that an issue about cache status is to blame.
Let's see what happened:
I sent a DNS resolve request of login.live.com to FreeDNS-Go. Apperantly it chose the clean upstream to handle my request. But at that time an error occured and it gave me an empty response, even without an SOA record.
After checking the log, I could figure out that it got an error while asking the clean upstream for the answer. But then it use the "cache" to answer clients' future questions. Of course we got nothing from empty cache.
I can completely be sure that both my upstreams are able to work, for I've tested the same domain with them.
It occurs randomly. So far I can't reproduce it deliberately.
Environment: Debian 10 Buster, FreeDNS-Go v2020.1.16

**Comment by louchenyao** [comment]
谢谢报告，我检查一下

**Comment by louchenyao** [comment]
我可能修好了错误，可以试下载新的版本：https://github.com/tuna/freedns-go/releases/tag/v2020.8.4

**Comment by qwqVictor** [comment]
谢谢，我更新一下评估一段时间。

**Comment by qwqVictor** [comment]
我想我可能有必要自行编译一下，看起来 commit [8d5ef57](https://github.com/tuna/freedns-go/commit/8d5ef57f2cdfccb640d9cd34eab241fa778cd01e) 涉及的问题比较重要。
建议以该 commit 之后编译的程序作为 release 的版本。

**Comment by louchenyao** [comment]
额，我其实重新上传了一下release 的内容，但是tag 指向的还是老的。

---
Chenyao Lou 娄晨耀
clou22@wisc.edu
louchenyao@gmail.com

**Comment by qwqVictor** [comment]
嗯好，目前还没有观测到问题。
我想这个 Issue 应该可以先关闭掉了，如果后续出现 bug 再 reopen。

**Comment by qwqVictor** [comment]
![image](https://user-images.githubusercontent.com/21100901/90868525-87882680-e3c9-11ea-8032-9e8d8ba0015f.png)

问题似乎再次出现，可能仍有代码存在 bug。

不过目前为止还无法确定一定是缓存的问题，我会持续关注直至确定问题。在此期间不必 reopen。
